services:
  - type: web
    name: reanphysics-api
    runtime: node
    plan: free
    rootDir: tutorial-site/server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: SERVER_URL
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
      - key: ABA_BASE_URL
        value: https://checkout-sandbox.payway.com.kh
      - key: ABA_MERCHANT_ID
        sync: false
      - key: ABA_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESET_EMAIL_FROM
        value: "ReanPhysics <onboarding@resend.dev>"
